
---------------------------------------------------------------------------
--	여기서부터 추가된 내용 													 --
---------------------------------------------------------------------------
-- 기존 테이블 삭제 (존재할 경우만)
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE ACCOUNTS PURGE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;


-- 테이블 생성
CREATE TABLE ACCOUNTS (
    num NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,		-- 회원번호
    id VARCHAR2(30) UNIQUE NOT NULL,										-- 회원 아이디
    pass VARCHAR2(30) NOT NULL,												-- 비밀번호
    name VARCHAR2(50),														-- 회원이름
    addr CLOB,																-- 주소
    phone VARCHAR2(20),														-- 전화번호
    gender VARCHAR2(10),													-- 성별(남성,여성)
    age NUMBER(3),															-- 나이
    email VARCHAR2(100) UNIQUE NOT NULL										-- 이메일주소
);

-- 관리자 계정 추가
INSERT INTO ACCOUNTS (
    id, pass, name, addr, phone, gender, age, email
) VALUES (
    'admin', 'admin', 'MASTER',
    '부산광역시', '01011111111', '남성', 30, 'admin@admin.com'
);

COMMIT;

-- 확인용
SELECT * FROM ACCOUNTS;

