
---------------------------------------------------------------------------
--	여기서부터 추가된 내용 													 --
---------------------------------------------------------------------------
-- 기존 테이블 삭제 (존재할 경우만)
DROP TABLE ACCOUNTS PURGE;


-- 테이블 생성
CREATE TABLE ACCOUNTS(
    num NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    category VARCHAR2(100) NOT NULL,
    title VARCHAR2(200) NOT NULL,
    author VARCHAR2(50) NOT NULL,
    content CLOB NOT NULL,
    image_data BLOB, -- 이미지 파일 자체가 들어갈 공간
    system_filename VARCHAR2(500), -- 파일명 기록용
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP
);

-- 관리자 계정 추가
INSERT INTO ACCOUNTS (
    id, pass, name, addr, phone, gender, age, email
) VALUES (
    'admin', 'admin', 'MASTER',
    '부산광역시', '01011111111', '남성', 30, 'ADMIN@admin.com'
);

COMMIT

-- 확인용
SELECT * FROM ACCOUNTS;

