DROP TABLE board_test PURGE;

CREATE TABLE board_test(
    num NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    category VARCHAR2(100) NOT NULL,
    title VARCHAR2(200) NOT NULL,
    author VARCHAR2(50) NOT NULL,
    content CLOB NOT NULL,
    -- 서버에 저장될 최종 파일명 (파일명 + num)
    system_filename VARCHAR2(500) UNIQUE, 
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    view_count NUMBER DEFAULT 0 NOT NULL CHECK (view_count >= 0)
);

INSERT INTO board_test (category, title, author, content, system_filename)
VALUES (
    '티셔츠', 
    '여름 신상', 
    'admin', 
    '상세 내용...', 
    -- '파일명' + '_' + '현재 전체 개수' + '.확장자'
    'tshirts' || '_' || (SELECT COUNT(*) FROM board_test) || '.jpg'
);

SELECT * FROM board_test;

----------------------------------------------------------------------
-- 상품 등록
----------------------------------------------------------------------
INSERT INTO board_test (
    category,
    title,
    author,
    content,
    img_url
) VALUES (
    'TOP>TSHIRT',
    '기본 반팔 티셔츠',
    'admin',
    '부드러운 면 소재의 기본 반팔입니다.',
    'css/img/upload/product/top/tshirt1.jpg'
);

COMMIT;

SELECT * FROM board_test;

----------------------------------------------------------------------
-- 상품 수정
----------------------------------------------------------------------
UPDATE board_test
SET 
    category = ?,
    title = ?,
    content = ?,
    img_url = ?,
    updated_at = SYSTIMESTAMP
WHERE num = ?;