DROP TABLE board_test PURGE;

CREATE TABLE board_test(
    num NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    category VARCHAR2(100) NOT NULL,
    title VARCHAR2(200) NOT NULL,
    author VARCHAR2(50) NOT NULL,
    content CLOB NOT NULL,
    -- 서버에 저장될 최종 파일명 (파일명 + num)
    system_filename VARCHAR2(500), 
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    view_count NUMBER DEFAULT 0 NOT NULL CHECK (view_count >= 0)
);