DROP TABLE board_test PURGE;

CREATE TABLE board_test(
    num NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    category VARCHAR2(100) NOT NULL,    -- 추가: 메뉴 분류 (티셔츠, 니트 등)
    title VARCHAR2(200) NOT NULL,
    author VARCHAR2(50) NOT NULL,
    content CLOB NOT NULL,
    img_url VARCHAR2(1000),             -- 추가: 사진 주소
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    view_count NUMBER DEFAULT 0 NOT NULL CHECK (view_count >= 0)
);