DROP TABLE products PURGE;

CREATE TABLE products (
    p_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    category VARCHAR2(100) NOT NULL,
    p_name VARCHAR2(200) NOT NULL,
    author VARCHAR2(50),
    p_desc CLOB NOT NULL,
    price NUMBER DEFAULT 0 NOT NULL,
    system_filename VARCHAR2(500), 
    -- 조회수 컬럼 추가 (기본값 0, NULL 허용 안 함)
    view_count NUMBER DEFAULT 0 NOT NULL, 
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP,
    updated_at TIMESTAMP DEFAULT SYSTIMESTAMP
);
--가짜 100개 데이터
BEGIN
    FOR i IN 1..100 LOOP
        INSERT INTO products (
            category, 
            p_name, 
            author, 
            p_desc, 
            price, 
            view_count
        ) VALUES (
            '카테고리' || MOD(i, 5),
            '상품명 ' || i,
            '관리자',
            '상세 설명 데이터 ' || i,
            1000 + (i * 100),
            0
        );
    END LOOP;
END;

commit
-- 1. 상품 등록 예시 (가격 컬럼 추가)
INSERT INTO products (category, p_name, author, p_desc, price, system_filename) 
VALUES (
    '티셔츠',
    '기본 반팔 티셔츠',
    'admin',
    '부드러운 면 소재의 기본 반팔입니다.',
    15000,
    'tshirt1.jpg' -- 경로 없이 파일명만 저장
);

INSERT INTO products (category, p_name, author, p_desc, price, system_filename) 
VALUES (
    '슈즈',
    '남아) 남색 로퍼',
    'admin',
    '편안한 착용감의 아동용 로퍼입니다.',
    35000,
    'shoes-boy140.jpg'
);

COMMIT;

-- 전체 상품 조회 (최신순)
SELECT * FROM products ORDER BY p_id DESC;

-- 카테고리별 검색 (예: 티셔츠만 보기)
SELECT * FROM products WHERE category = '티셔츠';

-- 상품명 키워드 검색 (예: '반팔'이 포함된 상품)
SELECT * FROM products WHERE p_name LIKE '%반팔%';

-- 특정 가격대 검색 (예: 2만원 이하 상품)
SELECT * FROM products WHERE price <= 20000;