-- products 테이블이 실제로 있는지 검증
SELECT table_name 
FROM user_tables 
WHERE table_name = 'PRODUCTS';

DROP TABLE products PURGE;

CREATE TABLE products (
    p_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    category VARCHAR2(100) NOT NULL,
    p_name VARCHAR2(200) NOT NULL,
    author VARCHAR2(50),
    p_desc CLOB NOT NULL,
    price NUMBER DEFAULT 0 NOT NULL,
    system_filename VARCHAR2(500), 
    -- 조회수 컬럼 추가 (기본값 0, NULL 허용 안 함)
    view_count NUMBER DEFAULT 0 NOT NULL, 
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP,
    updated_at TIMESTAMP DEFAULT SYSTIMESTAMP
);

--가짜 100개 데이터
BEGIN
    FOR i IN 1..100 LOOP
        INSERT INTO PRODUCTS (
            category,
            p_name,
            author,
            p_desc,
            price,
            view_count
        ) VALUES (
            '카테고리' || MOD(i,5),
            '상품명 ' || i,
            '관리자',
            '상세 설명 데이터 ' || i,
            1000 + (i * 100),
            0
        );
    END LOOP;
END;

COMMIT

-- 1. 상품 등록 예시 (가격 컬럼 추가)
INSERT INTO products (category, p_name, author, p_desc, price, system_filename) 
VALUES (
    '티셔츠',
    '기본 반팔 티셔츠',
    'admin',
    '부드러운 면 소재의 기본 반팔입니다.',
    15000,
    'top/tshirt1.jpg' -- 경로 : '중분류/파일명.확장자' (으)로 저장
);

INSERT INTO products (category, p_name, author, p_desc, price, system_filename) 
VALUES (
    '슈즈',
    '남아) 남색 로퍼',
    'admin',
    '편안한 착용감의 아동용 로퍼입니다.',
    35000,
    'shoes_bag/shoes-boy140.jpg' -- 경로 : '중분류/파일명.확장자' (으)로 저장
);

COMMIT
-- p_desc서부터 board_test 에서 가져온 sql --
INSERT INTO products (category, p_name, author, p_desc, price, system_filename)
VALUES (
    '티셔츠', 
    '여름 신상', 
    'admin', 
    '상세 내용...', 
    -- '파일명' + '_' + '현재 전체 개수' + '.확장자'
    
    'tshirts' || '_' || (SELECT COUNT(*) FROM products) || '.jpg'
);

SELECT * FROM products;

----------------------------------------------------------------------
-- 상품 등록
----------------------------------------------------------------------
INSERT INTO products (
    category,
    p_name,
    author,
    p_desc,
    price,
    system_filename
) VALUES (
    '티셔츠',
    '기본 반팔 티셔츠',
    'admin',
    '부드러운 면 소재의 기본 반팔입니다.',
    10000,
    'css/img/upload/product/top/tshirt1.jpg'
);

INSERT INTO products (
    category,
    p_name,
    author,
    p_desc,
    price,
    system_filename
) VALUES (
    '티셔츠',
    '여성) 스트라이프 반팔 T',
    'admin',
    '부드러운 면 소재의 스트라이프 무늬 반팔입니다.',
    10000,
    'css/img/upload/product/top/tshirt2.jpg'
);

INSERT INTO products (
    category,
    p_name,
    author,
    p_desc,
    price,
    system_filename
) VALUES (
    '티셔츠',
    '여성) [디즈니] 코튼 반팔 T',
    'admin',
    '부드러운 면 소재의 스트라이프 무늬 반팔입니다.',
    10000,
    'css/img/upload/product/top/tshirt3.jpg'
);

INSERT INTO products (
    category,
    p_name,
    author,
    p_desc,
    price,
    system_filename
) VALUES (
    '슈즈',
    '남아) 남색 로퍼',
    'admin',
    'null',
    10000,
    'css/img/upload/product/shoes_bag/shoes-boy140.jpg'
);

INSERT INTO products (
    category,
    p_name,
    author,
    p_desc,
    price,
    system_filename
) VALUES (
    '바지',
    '남아) 1+1 편안한 바지',
    'admin',
    'null',
    10000,
    'css/img/upload/product/bottom/pants-boy121.jpg'
);

INSERT INTO products (
    category,
    p_name,
    author,
    p_desc,
    price,
    system_filename
) VALUES (
    '바지',
    '남아) 1+1 조거 통 바지',
    'admin',
    'null',
    10000,
    'css/img/upload/product/bottom/pants-boy122.jpg'
);

INSERT INTO products (
    category,
    p_name,
    author,
    p_desc,
    price,
    system_filename
) VALUES (
    '바지',
    '남아) 1+1 조거 츄리닝 바지',
    'admin',
    'null',
    10000,
    'css/img/upload/product/bottom/pants-boy123.jpg'
);

INSERT INTO products (
    category,
    p_name,
    author,
    p_desc,
    price,
    system_filename
) VALUES (
    '머리띠',
    '여아) 파랑 리본',
    'admin',
    'null',
    10000,
    'css/img/upload/product/acc-girl0100.jpg'
);

INSERT INTO products (
    category,
    p_name,
    author,
    p_desc,
    price,
    system_filename
) VALUES (
    '머리띠',
    '여아) 파랑 리본',
    'admin',
    'null',
    10000,
    'css/img/upload/product/acc-girl0100.jpg'
);

INSERT INTO products (
    category,
    p_name,
    author,
    p_desc,
    price,
    system_filename
) VALUES (
    '블라우스',
    '여성) 씨쓰루 브이넥 검정 블라우스',
    'admin',
    'null',
    10000,
    'css/img/upload/product/top/blouse-lady008.jpg'
);

INSERT INTO products (
    category,
    p_name,
    author,
    p_desc,
    price,
    system_filename
) VALUES (
    '블라우스',
    '여성) 핑크 벌룬 반팔 블라우스',
    'admin',
    'null',
    10000,
    'css/img/upload/product/top/blouse-lady010pg'
);

INSERT INTO products (
    category,
    p_name,
    author,
    p_desc,
    price,
    system_filename
) VALUES (
    '속옷',
    '여성) 베이지 긴팔 신축성 내복',
    'admin',
    'null',
    10000,
    'css/img/upload/product/innnerwear/inner-lady031.jpg'
);

INSERT INTO products (
    category,
    p_name,
    author,
    p_desc,
    price,
    system_filename
) VALUES (
    '바지',
    '남아) 1+1 남색회색 1신축성 내복',
    'admin',
    'null',
    10000,
    'css/img/upload/product/innnerwear/'
);

INSERT INTO products (
    category,
    p_name,
    author,
    p_desc,
    price,
    system_filename
) VALUES (
    '속옷',
    '여성) 베이지 올인원',
    'admin',
    'null',
    10000,
    'css/img/upload/product/innnerwear/inner-lady032.jpg'
);

INSERT INTO products (
    category,
    p_name,
    author,
    p_desc,
    price,
    system_filename
) VALUES (
    '신발',
    '여성) 로퍼 블랙',
    'admin',
    'null',
    10000,
    'css/img/upload/product/shoes/loafer-lady055.jpg'
);

INSERT INTO products (
    category,
    p_name,
    author,
    p_desc,
    price,
    system_filename
) VALUES (
    '신발',
    '여성) 로퍼 블랙',
    'admin',
    'null',
    10000,
    'css/img/upload/product/shoes/maryjane-lady056.jpg'
);

INSERT INTO products (
    category,
    p_name,
    author,
    p_desc,
    price,
    system_filename
) VALUES (
    '원피스',
    '여성) 화이트리본 타이, 블랙 타이트 원피스',
    'admin',
    'null',
    10000,
    'css/img/upload/product/one-piece/pnepiece-lady021.jpg'
);

INSERT INTO products (
    category,
    p_name,
    author,
    p_desc,
    price,
    system_filename
) VALUES (
    '원피스',
    '여성) 블랙, 민소매 루즈 원피스',
    'admin',
    'null',
    10000,
    'css/img/upload/product/one-piece/onepiece-lady024.jpg'
);

INSERT INTO products (
    category,
    p_name,
    author,
    p_desc,
    price,
    system_filename
) VALUES (
    '속옷',
    '여성) 파지마 바지, 보라 그린 핑크, 할매바지',
    'admin',
    'null',
    10000,
    'css/img/upload/product/one-piece/pajamas-lady015.jpg'
);

INSERT INTO products (
    category,
    p_name,
    author,
    p_desc,
    price,
    system_filename
) VALUES (
    '바지',
    '여성) 그래이 슬랙스 통바지',
    'admin',
    'null',
    10000,
    'css/img/upload/product/bottom/pants-lady016.jpg'
);

INSERT INTO products (
    category,
    p_name,
    author,
    p_desc,
    price,
    system_filename
) VALUES (
    '스커트',
    '여성) 나무색, 옆트임, 6부, A라인',
    'admin',
    'null',
    10000,
    'css/img/upload/product/bottom/skirt-lady041.jpg'
);

INSERT INTO products (
    category,
    p_name,
    author,
    p_desc,
    price,
    system_filename
) VALUES (
    '스커트',
    '여성) A라인, 9부, 앞 핀턱',
    'admin',
    'null',
    10000,
    'css/img/upload/product/bottom/skirt-lady046.jpg'
);

INSERT INTO products (
    category,
    p_name,
    author,
    p_desc,
    price,
    system_filename
) VALUES (
    '쟈켓',
    '남성) 네이비 중간 길이 쟈켓',
    'admin',
    'null',
    10000,
    'css/img/upload/product/outer/jacket-men029.jpg'
);

COMMIT


-- 전체 상품 조회 (최신순)
SELECT * FROM products ORDER BY p_id DESC;

-- 카테고리별 검색 (예: 티셔츠만 보기)
SELECT * FROM products WHERE category = '티셔츠';

-- 상품명 키워드 검색 (예: '반팔'이 포함된 상품)
SELECT * FROM products WHERE p_name LIKE '%반팔%';

-- 특정 가격대 검색 (예: 2만원 이하 상품)
SELECT * FROM products WHERE price <= 20000;

COMMIT

-- product 테이블 조회
SELECT column_name
FROM user_tab_columns
WHERE table_name = 'PRODUCTS';

SELECT table_name 
FROM user_tables 
WHERE table_name = 'PRODUCTS';

--products 테이블에서 system_filename 조회
SELECT system_filename FROM products;